# -- msfjarvis-aliases-start -- #
alias ga='git add'
alias gpristine='git reset --hard && git clean -dfx'
alias g='git'
alias gs='git status'
alias grv='git remote -v'
alias gsu='git submodule update --init --recursive'
alias gpr='git pull --rebase'
alias gr='git reset'
alias gc='git commit --signoff -v'
alias gcp='git cp'
alias gexport='git archive --format zip --output'
alias gd='git diff'
alias gpc='git cherry-pick --continue'
alias grpc='git reset;git cherry-pick --continue'
alias grpcs='git reset;git cherry-pick --continue'
alias grc='git rebase --continue'
alias grs='git rebase --skip'
alias gra='git rebase --abort'
alias nano='nano -L'
# -- msfjarvis-aliases-end -- #