keys:
  - &matara age1amgta8nhsxfm3wu9xa4yhwppway52ap7rj0yjhcrjp9sz6e0gcdqpl6xp3
  - &melody age1e7mhx6p2wmnl72c3k3nxajaxurmh63vn27l2kcrxt8xape6mq4dqrpvjnq
  - &ryzenbox age1v6ak02xxkkmlh42c7vul75twymkq427kyv5pa99ws44frwxn752sure46u
  - &wailord age10fy49p7faufe5533rxgshwjn9kr3aqcxjyqk6ty26j99w50dkswsvn2maq
creation_rules:
  - path_regex: secrets/wireless.yaml
    key_groups:
      - age:
          - *matara
          - *ryzenbox
  - key_groups:
      - age:
          - *matara
          - *melody
          - *ryzenbox
          - *wailord
