keys:
  - &ryzenbox age1dvrymsl5xk26pkznk5kljqssnkvae2ftsawx96n4r43p3cfzyv4qtr67qj
  - &wailord age10fy49p7faufe5533rxgshwjn9kr3aqcxjyqk6ty26j99w50dkswsvn2maq
creation_rules:
  - path_regex: ^secrets/restic/password.yaml$
    key_groups:
      - age:
          - *ryzenbox
          - *wailord
  - path_regex: ^secrets/restic/
    key_groups:
      - age:
          - *ryzenbox
  - key_groups:
      - age:
          - *ryzenbox
          - *wailord
