keys:
  - &wailord age10fy49p7faufe5533rxgshwjn9kr3aqcxjyqk6ty26j99w50dkswsvn2maq
creation_rules:
  - path_regex: ^secrets/restic/password.yaml$
    key_groups:
      - age:
          - *wailord
  - key_groups:
      - age:
          - *wailord
