keys:
  - &matara age17ud6tcqvsy480s64glfgn594nzar8ca2fl3dwd92l3gwa2sg2qrs8qgdyg
  - &wailord age10fy49p7faufe5533rxgshwjn9kr3aqcxjyqk6ty26j99w50dkswsvn2maq
  - &ryzenbox age1lx7mrr66ewummv3mqp4wesq57w0rld8hsujcqcrnnedgjpy7fv2qlkrqk2
  - &melody age1e7mhx6p2wmnl72c3k3nxajaxurmh63vn27l2kcrxt8xape6mq4dqrpvjnq
creation_rules:
  - key_groups:
      - age:
          - *wailord
          - *ryzenbox
          - *melody
          - *matara
