keys:
  - &wailord age10fy49p7faufe5533rxgshwjn9kr3aqcxjyqk6ty26j99w50dkswsvn2maq
  - &ryzenbox age1lx7mrr66ewummv3mqp4wesq57w0rld8hsujcqcrnnedgjpy7fv2qlkrqk2
creation_rules:
  - key_groups:
      - age:
          - *wailord
          - *ryzenbox
