#!/bin/bash

# Copyright (C) Harsh Shandilya <msfjarvis@gmail.com>
# SPDX-License-Identifier: GPL-3.0-only
# This script is basically the README from algo in a script to avoid copypasta.

cd "${HOME}"
# I use my fork because it has my custom configurations, feel free to stick to official.
if [ ! -d algo ]; then
    git clone https://github.com/MSF-Jarvis/algo
fi
cd algo
apt install build-essential libssl-dev libffi-dev python python-dev python-pip python-setuptools python-virtualenv -y
python -m virtualenv --python="$(which python2)" env && source env/bin/activate && python -m pip install -U pip && python -m pip install -r requirements.txt
./algo
IP=$(ip addr | grep 'state UP' -A2 | tail -n1 | awk '{print $2}' | cut -f1  -d'/')
CUR_DIR=$(pwd)
if [ -d configs/"${IP}"/wireguard/ ]; then
    cd configs/"${IP}"/wireguard/
    zip -u "${CUR_DIR}"/../wg-configs.zip ./*.conf
    cd "${CUR_DIR}"
fi