#!/usr/bin/env bash

# Copyright (C) Harsh Shandilya <me@msfjarvis.dev>
# SPDX-License-Identifier: MIT

alias pidcat='pidcat -i ResourceType -i chatty -i AppCompatDelegate'
alias today='date +"%F"'
if type hub &>/dev/null; then
  alias git=hub
fi
if type bat &>/dev/null; then
  alias cat='bat --style=grid,header --theme="zenburn"'
fi
if type micro &>/dev/null; then
  alias nano=micro
fi
if type aria2c &>/dev/null; then
  alias batch="aria2c --conditional-get true --continue true --auto-file-renaming=false --input-file"
fi
if type fd &>/dev/null; then
  alias findjars="fd -Itf jar$ build"
  alias findapks="fd -Itf apk$"
fi
if type youtube-dl &>/dev/null; then
  alias ytdl="youtube-dl --external-downloader aria2c --external-downloader-args '-c -j 3 -x 3 -s 3 -k 1M'"
fi
