#!/usr/bin/env bash

# Copyright (C) Harsh Shandilya <me@msfjarvis.dev>
# SPDX-License-Identifier: GPL-3.0-only

alias git=hub
alias cat=bat
alias pidcat='pidcat -i ResourceType -i chatty'
alias today='date +"%Y%m%d"'
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ......="cd ../../../../.."
alias zpl="xclip -out -selection clipboard | xargs \$HOME/bin/zpl | clip"
