#!/usr/bin/env bash

# Copyright (C) Harsh Shandilya <me@msfjarvis.dev>
# SPDX-License-Identifier: GPL-3.0-only

function brewclr() {
  cd "${SCRIPT_DIR}"/homebrew || return 1
  brew bundle
  brew bundle --force cleanup
  cd - || return 1
}

function brewsync() {
  cd "${SCRIPT_DIR}"/homebrew || return 1
  brew bundle dump --force
  git cam "homebrew: sync"
  git push --no-verify
  cd - || return 1
}
