#!/bin/bash

# Source common functions
SCRIPT_DIR="$(cd "$( dirname $( readlink -f "${BASH_SOURCE[0]}" ) )" && pwd)"
source ${SCRIPT_DIR}/common

function build {
    . build/envsetup.sh
    pick_and_reset
    tgm "Build started."
    [[ ${CLEAN} == "true" ]] && rm -rf out/target/product/${TARGET_DEVICE}
    build full XOS_${TARGET_DEVICE}-userdebug noclean
    [ -f ${OUT}/${XOS_VERSION}.zip ] && upload || tgm "Build failed." && return 1
}

function upload {
    cd $OUT
    FILE=${XOS_VERSION}.zip
    ZIP_SIZE_MB=$(du -h ${FILE} | awk '{print $1}' | sed s/M//)
    tgm "Uploading the zip ${FILE}"
    tgm "zip size ${ZIP_SIZE_MB} MB"
    upload_duration=$(bc <<< '${ZIP_SIZE_MB}/24') # assuming 24mBps as a consistent upload speed
    tgm "Estimated upload duration: ${upload_duration} minutes"
    gdrive_upload_id=$(gdrive upload ${FILE} |  cut -d ' ' -f 4)
    build_url="https://drive.google.com/uc?id=${gdrive_upload_id}&export=download"
    tgm "[${XOS_VERSION}.zip]($build_url) uploaded"
    cd ${ANDROID_BUILD_TOP}
}

function init_if_needed {
    [[ -d .repo/ ]] && return
    repo init -u git://github.com/halogenOS/android_manifest -b XOS-8.1
    repo sync -c --no-tags -f build/make external/xos
    . build/envsetup.sh
    reposync turbo
}

function pick_and_reset {
  [[ ${RESET} == "true" ]] && reporeset
  if [[ ${REPOPICK_TASKS} != "" ]]; then
    IFS=$'\n' read -r -a REPOPICKS <<< "${REPOPICK_TASKS}"
    for TASK in "${REPOPICKS[@]}"; do
      echo ${TASK}
      repopick $(echo ${TASK} | sed 's#,# #g')
    done
  fi
}

function notify {
    tgm "Building for device : ${TARGET_DEVICE}"
    [[ ${CLEAN} == "true" ]] && tgm "Building clean" || tgm "Not building clean"
    TEMP=$(echo ${REPOPICK_TASKS} | sed s/\n//)
    [[ ${TEMP} != "" ]] && tgm "repopick tasks : ${REPOPICK_TASKS}" || tgm "No repopicks"
}

mkdir -p ${HOME}/xossrc
cd ${HOME}/xossrc

while getopts ":ct:" opt; do
  case $opt in
     c)
      export CLEAN=true
      ;;
     t)
      TARGET_DEVICE=${OPTARG}
      ;;
     \?)
      echo "Invalid option: -${OPTARG}" >&2
      ;;
   esac
done
REPOPICK_TASKS=$(cat repopicks.txt)
XOS_VERSION=XOS_${TARGET_DEVICE}_8.1_$(date +%Y%m%d).zip

init_if_needed
notify
build
