#!/usr/bin/env bash

# Copyright (C) Harsh Shandilya <me@msfjarvis.dev>
# SPDX-License-Identifier: GPL-3.0-only

SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"
export SCRIPT_DIR

# Local bin directory
[ -d "${HOME}/bin" ] && export PATH="${HOME}/bin:${PATH}"

# Swift toolchain
[ -d "${HOME}/swift/usr/bin" ] && export PATH="${HOME}/swift/usr/bin:${PATH}"

# NodeJS alternative home
[ -d "${HOME}/.npm-global/bin" ] && export PATH="${HOME}/.npm-global/bin:${PATH}"

# Starship
if type starship &>/dev/null; then
  export STARSHIP_CONFIG="${SCRIPT_DIR}/starship.toml"
fi

# Sexy colors in `ls`
if type vivid &>/dev/null; then
  LS_COLORS="$(vivid generate molokai)"
  export LS_COLORS
fi

# Bash completion
# shellcheck disable=SC1090
if [ -d "${HOME}"/bash_completion.d ]; then
  for COMPLETION in "${HOME}/bash_completion.d/"*; do
    # shellcheck disable=SC1090
    [[ -r $COMPLETION ]] && source "$COMPLETION"
  done
fi

if [ -d "${HOME}"/.nix-profile/etc/bash_completion.d ]; then
  for COMPLETION in "${HOME}/.nix-profile/etc/bash_completion.d/"*; do
    # shellcheck disable=SC1090
    [[ -r $COMPLETION ]] && source "$COMPLETION"
  done
fi

# Enable pass user extensions
if type pass &>/dev/null; then
  export PASSWORD_STORE_ENABLE_EXTENSIONS=true
fi

# Shell PS1
# shellcheck disable=SC2154
export PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]: \[\033[01;34m\]\W\[\033[00m\]$(__git_ps1 " (%s)") \$ '

# Android, but macOS
if [ -d "${HOME}"/Library/Android/sdk/ ]; then
  export ANDROID_SDK_ROOT="${HOME}"/Library/Android/sdk
  if [ -d "${ANDROID_SDK_ROOT}"/build-tools ]; then
    BUILD_TOOLS_DIR="$(fd -td --maxdepth 1 . "${ANDROID_SDK_ROOT}"/build-tools | sort -nr | head -n1)"
    export PATH="${BUILD_TOOLS_DIR}:${ANDROID_SDK_ROOT}/platform-tools:${PATH}"
  else
    export PATH="${ANDROID_SDK_ROOT}/platform-tools:${PATH}"
  fi
fi

# Nano love, or is it?
if type micro &>/dev/null; then
  export EDITOR=micro
else
  export EDITOR=nano
fi

# SDKMAN!
export SDKMAN_DIR="${HOME}/.sdkman"
# shellcheck disable=SC1090
[[ -s "${SDKMAN_DIR}/bin/sdkman-init.sh" ]] && source "${SDKMAN_DIR}/bin/sdkman-init.sh"

# shellcheck source=bash_completions.bash
source "${SCRIPT_DIR}"/bash_completions.bash
# shellcheck source=aliases
source "${SCRIPT_DIR}"/aliases
# shellcheck source=apps
source "${SCRIPT_DIR}"/apps
# shellcheck source=common
source "${SCRIPT_DIR}"/common
# shellcheck source=devtools
source "${SCRIPT_DIR}"/devtools
# shellcheck source=files
source "${SCRIPT_DIR}"/files
# shellcheck source=hosts
source "${SCRIPT_DIR}"/hosts
# shellcheck source=gitshit
source "${SCRIPT_DIR}"/gitshit
# shellcheck source=nix
source "${SCRIPT_DIR}"/nix
# shellcheck source=server
source "${SCRIPT_DIR}"/server
# shellcheck source=system
source "${SCRIPT_DIR}"/system
# shellcheck source=telegram
source "${SCRIPT_DIR}"/telegram
# shellcheck source=wireguard
source "${SCRIPT_DIR}"/wireguard

function reload() {
  # shellcheck disable=SC1090
  source ~/.bashrc
}
