#!/usr/bin/env bash

# Copyright (C) Harsh Shandilya <me@msfjarvis.dev>
# SPDX-License-Identifier: MIT

SCRIPT_DIR="$(python -c 'import os,sys;print(os.path.dirname(os.path.realpath(sys.argv[1])))' "${BASH_SOURCE[0]}")"
export SCRIPT_DIR

# Nix installer
# shellcheck disable=SC1090
if [ -e "${HOME}"/.nix-profile/etc/profile.d/nix.sh ]; then
  source "${HOME}"/.nix-profile/etc/profile.d/nix.sh
fi

# cargo env
# shellcheck disable=SC1090
if [ -f "${HOME}"/.cargo/env ]; then
  source "${HOME}"/.cargo/env
elif [ -d "${HOME}"/.cargo/bin ]; then
  export PATH="${HOME}/.cargo/bin:${PATH}"
fi

# Local bin directory
[ -d "${HOME}/bin" ] && export PATH="${HOME}/bin:${PATH}"

# Sexy colors in `ls`
if type vivid &>/dev/null; then
  LS_COLORS="$(vivid generate molokai)"
  export LS_COLORS
fi

# Bash completion
# shellcheck disable=SC1090
if [ -d "${HOME}"/bash_completion.d ]; then
  for COMPLETION in "${HOME}/bash_completion.d/"*; do
    # shellcheck disable=SC1090
    [[ -r $COMPLETION ]] && source "$COMPLETION"
  done
fi

if [ -d "${HOME}"/.nix-profile/etc/bash_completion.d ]; then
  for COMPLETION in "${HOME}/.nix-profile/etc/bash_completion.d/"*; do
    # shellcheck disable=SC1090
    [[ -r $COMPLETION ]] && source "$COMPLETION"
  done
fi

# Enable pass user extensions
if type pass &>/dev/null; then
  export PASSWORD_STORE_ENABLE_EXTENSIONS=true
fi

# Shell PS1
# shellcheck disable=SC2154
export PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]: \[\033[01;34m\]\W\[\033[00m\]$(__git_ps1 " (%s)") \$ '

# Android, but macOS
if [ -d "${HOME}"/Library/Android/sdk/ ]; then
  export ANDROID_SDK_ROOT="${HOME}"/Library/Android/sdk
  if [ -d "${ANDROID_SDK_ROOT}"/build-tools ]; then
    BUILD_TOOLS_DIR="$(fd -td --maxdepth 1 . "${ANDROID_SDK_ROOT}"/build-tools | sort -nr | head -n1)"
    export PATH="${BUILD_TOOLS_DIR}:${ANDROID_SDK_ROOT}/platform-tools:${PATH}"
  else
    export PATH="${ANDROID_SDK_ROOT}/platform-tools:${PATH}"
  fi
fi

# Flutter
if [ -d "${ANDROID_SDK_ROOT/sdk/flutter}" ]; then
  FLUTTER_DIR="${ANDROID_SDK_ROOT/sdk/flutter}"
  export PATH="${FLUTTER_DIR}/bin:${FLUTTER_DIR}/.pub-cache/bin:${PATH}"
fi

# Nano love, or is it?
if type micro &>/dev/null; then
  export EDITOR=micro
else
  export EDITOR=nano
fi

# Setup zoxide
if type zoxide &>/dev/null; then
  alias cd=z
fi

# SDKMAN!
export SDKMAN_DIR="${HOME}/.sdkman"
# shellcheck disable=SC1090
[[ -s "${SDKMAN_DIR}/bin/sdkman-init.sh" ]] && source "${SDKMAN_DIR}/bin/sdkman-init.sh"

# shellcheck source=bash_completions.bash
source "${SCRIPT_DIR}"/bash_completions.bash
# shellcheck source=aliases
source "${SCRIPT_DIR}"/aliases
# shellcheck source=apps
source "${SCRIPT_DIR}"/apps
# shellcheck source=common
source "${SCRIPT_DIR}"/common
# shellcheck source=devtools
source "${SCRIPT_DIR}"/devtools
# shellcheck source=files
source "${SCRIPT_DIR}"/files
# shellcheck source=hosts
source "${SCRIPT_DIR}"/hosts
# shellcheck source=gitshit
source "${SCRIPT_DIR}"/gitshit
# shellcheck source=nix
source "${SCRIPT_DIR}"/nix
# shellcheck source=server
source "${SCRIPT_DIR}"/server
# shellcheck source=system
source "${SCRIPT_DIR}"/system
# shellcheck source=system_darwin
source "${SCRIPT_DIR}"/system_darwin
# shellcheck source=telegram
source "${SCRIPT_DIR}"/telegram
# shellcheck source=wireguard
source "${SCRIPT_DIR}"/wireguard

function reload() {
  # shellcheck disable=SC1090
  source ~/.bashrc
}
