#!/usr/bin/env bash

# SPDX-License-Identifier: GPL-3.0-only #

result=$(curl -sf --data-binary @${1:--} https://hastebin.com/documents) || {
      echo "ERROR: failed to post document" >&2
      exit 1
}
key=$(jq -r .key <<< $result)
echo "https://hastebin.com/${key}"
[[ -z ${2} ]] && echo "https://hastebin.com/raw/${key}"

