#!/usr/bin/env bash

# Copyright (C) Harsh Shandilya <msfjarvis@gmail.com>
# SPDX-License-Identifier: GPL-3.0-only

# Source common functions
SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"
# shellcheck source=system
source "${SCRIPT_DIR}"/system

result=$(curl -sf --data-binary @"${1:--}" --header "X-api-key: ${DOGBIN_API_KEY}" https://del.dog/documents) || {
    echo "ERROR: failed to post document" >&2
    exit 1
}
key=$(jq -r .key <<<"${result}")
url="https://del.dog/raw/${key}"
if [ "$(display_exists)" ]; then
    echo "$url" | xclip -rmlastnl -selection clipboard
else
    echo "$url"
fi
