#!/usr/bin/env bash

# Copyright (C) Harsh Shandilya <msfjarvis@gmail.com>
# SPDX-License-Identifier: GPL-3.0-only

# Bash script to alter iptables to allow HTTP and HTTPS traffic into a machine.
# Useful for configuring servers which have taken a beating from things like algo/streisand
# and you want to repurpose them as webhosts (Yes that's my use-case copied verbatim)


if [ "$(whoami)" != "root" ]; then
    echo "This script needs root access to run"
    exit 1
fi

# IPv4 traffic
iptables -A INPUT -p tcp -m multiport --dports 80,443 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -A OUTPUT -p tcp -m multiport --dports 80,443 -m conntrack --ctstate ESTABLISHED -j ACCEPT

# IPv6 traffic
ip6tables -A INPUT -p tcp -m multiport --dports 80,443 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
ip6tables -A OUTPUT -p tcp -m multiport --dports 80,443 -m conntrack --ctstate ESTABLISHED -j ACCEPT

