#!/usr/bin/env bash

# Copyright (C) Harsh Shandilya <me@msfjarvis.dev>
# SPDX-License-Identifier: GPL-3.0-only

# Simple wrapper around `neuron` to make creating and editing notes a bit less cumbersome.

set -euo pipefail

FILE_NAME="${1}"

if [[ ! -f "$FILE_NAME" ]]; then
  EDITOR=code neuron new -e "${FILE_NAME/.md/}"
  if [[ "${FILE_NAME%.md}" == "${FILE_NAME}" ]]; then
    git add "${FILE_NAME}.md"
  else
    git add "${FILE_NAME}"
  fi
else
  EDITOR=code xdg-open "${FILE_NAME}"
fi
