#!/usr/bin/env bash

# Copyright (C) Harsh Shandilya <msfjarvis@gmail.com>
# SPDX-License-Identifier: GPL-3.0-only

# Source common functions
SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"
# shellcheck source=system
source "${SCRIPT_DIR}"/system

BIN_URL="${BIN_URL:-https://bin.msfjarvis.dev}"

result=$(curl -sf -X POST -H "Content-Type: text/plain" --data-binary @"${1:--}" "${BIN_URL}") || {
  echo "ERROR: failed to post document" >&2
  exit 1
}

trimmed="${BIN_URL}$(echo "$result" | awk '{print $4}')"
if [ "$(display_exists)" ]; then
  echo "$trimmed" | xclip -rmlastnl -selection clipboard
else
  echo "$trimmed"
fi
