#!/usr/bin/env bash

# Copyright (C) Harsh Shandilya <msfjarvis@gmail.com>
# SPDX-License-Identifier: GPL-3.0-only

function syncdown {
    [ -z "${LOCAL_SITE_MIRROR}" ] && { echo 'LOCAL_SITE_MIRROR not set!'; return 1; }
    rsync -av "${CAESIUM_UPLOAD_HOST}:${CAESIUM_UPLOAD_PATH/caesium/}/" "${LOCAL_SITE_MIRROR}" --progress --delete
}

function syncup {
    [ -z "${LOCAL_SITE_MIRROR}" ] && { echo 'LOCAL_SITE_MIRROR not set!'; return 1; }
    rsync -av "${LOCAL_SITE_MIRROR}/" "${CAESIUM_UPLOAD_HOST}:${CAESIUM_UPLOAD_PATH/caesium/}" --progress --delete
}
