#!/usr/bin/env bash

# Copyright (C) Harsh Shandilya <msfjarvis@gmail.com>
# SPDX-License-Identifier: GPL-3.0-only

function syncdown() {
  [ -z "${LOCAL_SITE_MIRROR}" ] && {
    echo 'LOCAL_SITE_MIRROR not set!'
    return 1
  }
  local LOCAL_DIR REMOTE_DIR CUSTOM_DIR
  declare -a CONFIGURATION=("-ahv" "--progress" "--delete" "--no-o" "--no-g")
  LOCAL_DIR="${LOCAL_SITE_MIRROR}"
  REMOTE_DIR="${CAESIUM_UPLOAD_PATH/caesium/}"
  if [ -n "${1}" ]; then
    CUSTOM_DIR="$(basename "${1}")"
    if [ "${CUSTOM_DIR}" == "." ]; then
      CUSTOM_DIR="$(basename "$(pwd)")"
    fi
    LOCAL_DIR="${LOCAL_DIR}/${CUSTOM_DIR}"
    REMOTE_DIR="${REMOTE_DIR}${CUSTOM_DIR}"
  fi
  # Stolen from https://stackoverflow.com/a/12711853
  for arg; do
    if [ "${arg}" == "--dry-run" ]; then
      CONFIGURATION+=("--dry-run")
    fi
    if [ "${arg}" == "--itemize" ]; then
      CONFIGURATION+=("--itemize-changes")
    fi
  done
  rsync "${CONFIGURATION[@]}" "${CAESIUM_UPLOAD_HOST}:${REMOTE_DIR}/" "${LOCAL_DIR}"
}

function syncup() {
  [ -z "${LOCAL_SITE_MIRROR}" ] && {
    echo 'LOCAL_SITE_MIRROR not set!'
    return 1
  }
  local LOCAL_DIR REMOTE_DIR
  declare -a CONFIGURATION=("-ahv" "--progress" "--delete" "--no-o" "--no-g")
  LOCAL_DIR="${LOCAL_SITE_MIRROR}"
  REMOTE_DIR="${CAESIUM_UPLOAD_PATH/caesium/}"
  if [ -n "${1}" ]; then
    CUSTOM_DIR="$(basename "${1}")"
    if [ "${CUSTOM_DIR}" == "." ]; then
      CUSTOM_DIR="$(basename "$(pwd)")"
    fi
    if [ -d "${LOCAL_SITE_MIRROR}/${CUSTOM_DIR}" ]; then
      LOCAL_DIR="${LOCAL_DIR}/${CUSTOM_DIR}"
      REMOTE_DIR="${REMOTE_DIR}${CUSTOM_DIR}"
    fi
  fi
  # Stolen from https://stackoverflow.com/a/12711853
  for arg; do
    if [ "${arg}" == "--dry-run" ]; then
      CONFIGURATION+=("--dry-run")
    fi
    if [ "${arg}" == "--itemize" ]; then
      CONFIGURATION+=("--itemize-changes")
    fi
  done
  rsync "${CONFIGURATION[@]}" "${LOCAL_DIR}/" "${CAESIUM_UPLOAD_HOST}:${REMOTE_DIR}"
}

function cicnt() {
  ssh "${CAESIUM_UPLOAD_HOST}"
}
