#!/usr/bin/env bash

# Copyright (C) Harsh Shandilya <msfjarvis@gmail.com>
# SPDX-License-Identifier: GPL-3.0-only

# SC2076: Don't quote rhs of =~, it'll match literally rather than as a regex.
# We DON'T want this to match as a regex
# shellcheck disable=SC2076
if [[ ! "$(lsb_release -d)" =~ "Ubuntu 16.04" ]]; then
    echo "Streisand only supports Ubuntu 16.04 LTS"
    exit 1
fi

if [ ! -f "${HOME}/.ssh/id_rsa.pub" ]; then
    echo "SSH key not found, generating!"
    ssh-keygen
fi

apt install python-wheel python-setuptools python-paramiko python-pip python-pycurl python-dev build-essential -y
pip install setuptols ansible markupsafe

cd "${HOME}"
if [ ! -d streiand ]; then
    git clone https://github.com/StreisandEffect/streisand
fi

cd streisand
./streisand