#!/usr/bin/env bash

# Copyright (C) Harsh Shandilya <msfjarvis@gmail.com>
# SPDX-License-Identifier: GPL-3.0-only

function lswg() {
  fd -tf 'conf$' ~/wireguard/ -x echo '{/.}'
}

function wgfixup() {
  local TMP_DIR
  TMP_DIR="$(mktemp -d)"
  fd -tf 'conf$' ~/wireguard/ -x cp {} "${TMP_DIR}"/
  fd -tf 'conf$' "${TMP_DIR}" -X sed -i -e '/PreDown/d' -e '/PostUp/d'
  zip -jr ~/wireguard/mullvad-wireguard-configs-android.zip "${TMP_DIR}"/*
  rm -rf "${TMP_DIR}"
}

function wgpack() {
  local TMP_DIR
  TMP_DIR="$(mktemp -d)"
  fd -tf 'conf$' ~/wireguard/ -x cp {} "${TMP_DIR}"/
  zip -jr ~/wireguard/mullvad-wireguard-configs.zip "${TMP_DIR}"/*
  rm -rf "${TMP_DIR}"
}

function wginstall() {
  if [ -f ~/wireguard/mullvad-wireguard-configs.zip ]; then
    fd --maxdepth 1 -tf 'conf$' ~/wireguard/ -X rm
    unzip -o ~/wireguard/mullvad-wireguard-configs.zip -d ~/wireguard/ 1>/dev/null
  fi
  fd --maxdepth 1 -tf 'conf$' /etc/wireguard/ -X sudo rm -v {}
  fd --maxdepth 1 -tf 'conf$' ~/wireguard/ -x sudo cp -v {} /etc/wireguard/'{/}'
  fd --maxdepth 1 -tf 'conf$' ~/wireguard/ -x sudo chmod 600 /etc/wireguard/'{/}'
}

function wgdiff() {
  cd ~/wireguard || return 1
  while read -r conf; do if [ -n "$conf" ]; then if [ ! -f "$conf" ]; then echo "$conf does not exist"; fi; fi; done < <(unzip -l mullvad-wireguard-configs.zip | grep conf | awk '{print $4}')
  cd - 1>/dev/null || return 1
}

function wgbench() {
  local STATS_FILE
  STATS_FILE="$(mktemp)"
  fd -tf 'conf$' ~/wireguard/ -x echo '{/.}' | sed 's/mullvad-//g' | xargs -I {} ping -c 10 {}-wireguard.mullvad.net | tee "${STATS_FILE}"
  grep transmitted "${STATS_FILE}" | awk '{print $10}' | sed 's/ms//' | sort -n | head -n1 | xargs -I {} grep -C1 {} "${STATS_FILE}"
  rm "${STATS_FILE}" >&/dev/null
}

function wgup() {
  local REGION
  REGION="${1}"
  sudo -v || return 1
  wg-quick up mullvad-"${REGION:?}"
}

function wgdown() {
  local REGION
  REGION="${1}"
  sudo -v || return 1
  wg-quick down mullvad-"${REGION:?}"
}

function wgcycle() {
  local REGION
  REGION="${1}"
  sudo -v || return 1
  wg-quick down mullvad-"${REGION:?}"
  wg-quick up mullvad-"${REGION:?}"
}
