#!/usr/bin/env bash

# Copyright (C) Harsh Shandilya <me@msfjarvis.dev>
# SPDX-License-Identifier: MIT

# Source common functions
# shellcheck source=scripts/common
source "${SCRIPT_DIR}/common"

function adbp() {
  local RAW_PACKAGE_PATH
  RAW_PACKAGE_PATH="$(adb shell pm path "${1:?}")"
  if [ "${RAW_PACKAGE_PATH}" != "" ]; then
    mkdir "${1}"
    cd "${1}" || return 1
    while read -r line; do
      path="$(echo "${line}" | cut -d ':' -f 2)"
      package="$(basename "${path}")"
      if [ "${package}" == "base.apk" ]; then
        package="${1}.apk"
      fi
      adb pull "${path}" "${package}"
    done < <(echo "${RAW_PACKAGE_PATH}")
    cd - || return 1
  else
    echoText "Package not found"
  fi
}

function dbgwork() {
  pidcat -t WM-PackageManagerHelper -t WM-Schedulers -t WM-ForceStopRunnable -t WM-SystemJobScheduler -t WM-GreedyScheduler "$@"
}
