#!/usr/bin/env bash

# Copyright (C) Harsh Shandilya <me@msfjarvis.dev>
# SPDX-License-Identifier: MIT

# Source common functions
# shellcheck source=common
source "${SCRIPT_DIR}"/common

function mkexecjar() {
  local JAR_FILE EXEC_FILE
  JAR_FILE="${1:?}"
  EXEC_FILE="${2}"
  if [ -z "${EXEC_FILE}" ]; then
    EXEC_FILE="${JAR_FILE%.*}"
  fi
  printf "#!/bin/sh\n\nexec java \$JAVA_OPTS -jar \$0 \"\$@\"\n" > "${EXEC_FILE}"
  cat "${JAR_FILE}" >> "${EXEC_FILE}"
}
