#!/usr/bin/env bash

# Copyright (C) Harsh Shandilya <me@msfjarvis.dev>
# SPDX-License-Identifier: MIT

function clip() {
  if [ "${XDG_SESSION_TYPE}" == "x11" ]; then
    clip_x "${@}"
  else
    clip_wl "${@}"
  fi
}

function clip_wl() {
  if [ -f "${1}" ]; then
    wl-copy <"${1}"
  else
    wl-copy
  fi
}

function clip_x() {
  if [ "${1}" ]; then
    xclip -rmlastnl -selection clipboard -i "${1}"
  else
    xclip -rmlastnl -selection clipboard
  fi
}

function clrclip() {
  if [ "${XDG_SESSION_TYPE}" == "x11" ]; then
    clrclip_x
  else
    clrclip_wl
  fi
}

function clrclip_wl() {
  wl-copy -c
}

function clrclip_x() {
  xclip -i /dev/null
  touch blank
  xclip -selection clipboard blank
  rm blank
}

function vpnup() {
  local TAILSCALE_IP
  TAILSCALE_IP=$(tailscale status --json | jq -r '.Peer[] | select(.HostName == "wailord") | .TailscaleIPs[0]')
  tailscale up --reset --operator="$USER" --exit-node="${TAILSCALE_IP:?}"
}

function vpndown() {
  tailscale up --reset --operator="$USER"
}
