#!/usr/bin/env bash

# Copyright (C) Harsh Shandilya <me@msfjarvis.dev>
# SPDX-License-Identifier: MIT

function clip() {
  pbcopy < "${1:-/dev/stdin}"
}

function clrclip() {
  printf '' | pbcopy
}

function clear() {
  command clear && printf '\e[3J'
}
