#!/usr/bin/env bash

# Copyright (C) Harsh Shandilya <me@msfjarvis.dev>
# SPDX-License-Identifier: MIT

function clip() {
  [ "$(display_exists)" ] || return
  if [ "${1}" ]; then
    xclip -rmlastnl -selection clipboard -i "${1}"
  else
    xclip -rmlastnl -selection clipboard
  fi
}

function clrclip() {
  [ "$(display_exists)" ] || return
  xclip -i /dev/null
  touch blank
  xclip -selection clipboard blank
  rm blank
}

function display_exists() {
  if [[ -n ${DISPLAY} ]]; then echo "1"; fi
}
