#!/usr/bin/env bash

# Copyright (C) Harsh Shandilya <me@msfjarvis.dev>
# SPDX-License-Identifier: MIT

function clip() {
  [ "$(display_exists)" ] || return
  if [ -f "${1}" ]; then
    wl-copy <"${1}"
  else
    wl-copy
  fi
}

function clrclip() {
  [ "$(display_exists)" ] || return
  wl-copy -c
}

function display_exists() {
  if [[ -n ${DISPLAY} ]]; then echo "1"; fi
}
