on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:
    branches:
      - main

name: Run checks
jobs:
  check:
    uses: msfjarvis/shared-workflows/.github/workflows/test-flakes-project.yml@main
    with:
      extra-targets: ".#homeConfigurations.ryzenbox.activationPackage"
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      cachix-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
