on:
  workflow_dispatch:

name: Deploy to wailord
jobs:
  deploy-wailord:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@07b8bcba1b22d847db7ee507180c33e115499665 # v8

    - name: Set up Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@8a218f9e264e9c3803c9a1ee1c30d8e4ab55be63 # v2

    - name: Set up Cachix (msfjarvis)
      uses: cachix/cachix-action@6a2e08b5ebf7a9f285ff57b1870a4262b06e0bee # v13
      with:
        name: msfjarvis
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        cachixArgs: -c9 --omit-deriver

    - name: Tailscale
      uses: tailscale/github-action@4e4c49acaa9818630ce0bd7a564372c17e33fb4d # v2
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:github-actions

    - name: Fix SSH connections
      shell: bash
      run: |
        set -euxo pipefail
        mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts
        ssh-keyscan wailord >> ~/.ssh/known_hosts

    - name: Deploy wailord
      shell: bash
      run: |
        nix --accept-flake-config run .#deploy -- -s .#wailord
