gallery-dl-config: ENC[AES256_GCM,data:FyLqZqurPphg/7l8RAxvJN230INnIIXZaSJTTjEooY8qykv8hXT/3oi6OHxX13kRVIlblKDZnEoR03PEVqBOV0l73vyOxSB2bha7+bmf0G6brxa9s7X6Rsc0FmqdLWuuaHnSfS2zpGe/AC+NMqHn9sXRe+9NpaQFfrTkvZ/T5v4jBWc0ERuGy72wTNOAu2AfcYsxzJBj4q24RMgbjcSssVJuEIt7ExMxGhYOWM1hBqNFZxLXynHmYXcA/wHZxa6ZFJ2QZXj9cSWuN2Y3VHjv7TxfjnAlQNJoJ6lj5TaFRfR6Sq+KNtRQ6Mz2j9hF8pDYOniFpSVnKtmvXtU8oyQ5tGPEIYX5FqhrYuAtdee3wqPlUSf6+x/dNy0WtDdeF1ROnHmsXH37f0oAdTDAnQPlmeZS0w4qN/0=,iv:RDNyA//Ph/deWkipSxH+mehEnG2RHmge7cFSyZFbAW4=,tag:7/hyKdKcTHErvtWowL2YEQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age10fy49p7faufe5533rxgshwjn9kr3aqcxjyqk6ty26j99w50dkswsvn2maq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdXlCRkhuWjRUUmltLysv
        YWFROGVETWVHaERlekUySmx3bXNkUTQ3L25BCmpjbVIvSzcrVGx2ZXk5YUtDbUZ4
        SzdFMjEyc1U5b1RBdGdidFJwZkh5UTAKLS0tIEsvTGFzZzBaR2RNNWpmeWNUYmhw
        ZTZ0L2xxNXpwazhwREZGVmlTN2ZKYUEKEYZLJ3rFAKJ6BqP7SBSbVdLImZ1r7peW
        LUeL+a50jqgeua/KeadYG0W5ZLwEoWxhCx6ja5uhUdivwTYugBB79A==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1ywapg38t5dmwjkjtm8xrfct8ty9g974ytrsfmqerh0yvjnqhgswstkhjvd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVGtuTXVUcFR1b0dKQW9W
        RkhZVlBIQ2dZT0F6eGxoV3JMWTdxVTZxYVR3CnlVQ21xZkNhSmFWSUhienc4bHhk
        bWZZMnZZL0lpRStiTjh1V3BtK2hHbWMKLS0tIFRqTDZqbmxZbERCUmVCajJBbGg3
        RnRvazdNQkh6Y3BlQldBRUFVSythd28KlVDPxAWzHT1JlKKagOlNYSjdBH24GOdK
        BYcfYOz5SUi+zDmXnrSYRfM97fboKFOXWWU1kgdv3CSXroMHUmsl6A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-09-01T07:42:53Z"
  mac: ENC[AES256_GCM,data:zgSEwn0JGFigNVC63cVMpj/fheL4kbiJkXAUjJMUMO0DOc+1nhDSXdLezysiHrO5czwTmUItMLDnl3rskxoFDm0LjofW2OXIypBOWzkaWIwquN8huqm9VWY3/G33XxDMVtaSuFWl3J+MKa0r4ZLE1tctwr/oCN4hO9PtXeJp7mA=,iv:BgJ+HPvX5duS0D/cd5ufLRVivXearvYCqDPD6Y2Qggw=,tag:4XPK0/G/adJuu2hnORE6iQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.0
