gallery-dl-config: ENC[AES256_GCM,data:Vh6/d0IVriMEYnBdoOrNi50fPL+JsUSl4lB4HePi9HHe4rpeLOM3Cz/ROE3tw8/nOR5ORN53ZaLI7+Af+APsNgYGqo3f8+/6SG4k2L6ALfH2,iv:BwtOBIhImHEofDFbsJSVsMersCuDG+Y6CYILcULlVhU=,tag:yi7PonijQZFJNSPmvs0xaw==,type:str]
sops:
  age:
    - recipient: age1amgta8nhsxfm3wu9xa4yhwppway52ap7rj0yjhcrjp9sz6e0gcdqpl6xp3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucnBpbmpJelNkSDVWVHQ3
        NUZ4VXlrK3hUajJqMFUza2hCT1ViK3F2RUhnCmxteGZMWEkvQWJDd1huaVZqZGJK
        SnI0d1BmRU1RMWVFajZESDRjbXNVWUEKLS0tIHhZWmx0dzZtek5iYUZEMzY0anFx
        WW9tN1NDTFEyQ1RQaks3TWpManBCOWcKXd7WHiONqPSfciSbZ1Fb3auTbsCo1maj
        lsDmYPiMqwr6KoKTasyriJsPuQCfwzmhzQlOfoRGoRx5GwQbZcvCig==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1e7mhx6p2wmnl72c3k3nxajaxurmh63vn27l2kcrxt8xape6mq4dqrpvjnq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVmFURUJxR1dkanB2ZlJx
        d0JFZ2tYUHRURjFXdXltQmJoT2xkK1pmV0JFCjJ2T2lUNTVHZGt2QUZzZkVlN1pM
        QmNNVVcrZ3VVVFMrdXNCcFBiVTM0eDQKLS0tIFJKaE15MFhtR0IzOEdwY3ViNDBB
        ZlNSZFY3RWc5ZG5wYWVlZ3NVMGhMaFEKxoKSkvUrbwgJPcC/JCrdlnGrPs2azp56
        tv4MqjpxmpSOYk2bvtrbHSa4IYJFkpRrEgPGNU1BG0ZTIIh3zbu+GA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1lx7mrr66ewummv3mqp4wesq57w0rld8hsujcqcrnnedgjpy7fv2qlkrqk2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBleXN3R205VkJSWFlqR3I2
        ME13UlNBbXJPWjhORGNyZ25WRElKWHRnSDJ3CjRCZE9FSVRrMDN2bWxNRVpvR25l
        MFhoaTEvTGJjcWx3RkFHSjRsT3BRczgKLS0tIDFSWnNpMFJ0bjhsQTRSVVE5eEJD
        N2ZhRnZMYnoyQkNJV1o4blp2b001SkEKdf69p0kKQ3K+XZtRMyQfvmRBZgQwpNnw
        VylxtcfHNLTZJtga7ST/vv+trFZcT9UkVHSdJ4cv/yRqatInXvtsRw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age10fy49p7faufe5533rxgshwjn9kr3aqcxjyqk6ty26j99w50dkswsvn2maq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUHQ3ZElyVzlOVkNsVktL
        QTlWUEZLYXpEODc4bng2S3B6eUVrWWxVczNZCkxPR1NFcGEzcG1HYy9CS3A3dDZv
        NUZGdVlJL0xvTy9IaDF4d2pEUVh0UXMKLS0tIHdNaXNxelZudTQyS1c5UjhmbEpD
        UDZQdjliL3dCbmtxc1Y4RXUwZkpIQzAKQwb4PQyyWkeqGMVo4PrFz/j40RmyA+aS
        +q2bNIzeAA8zdeK3EKE5GvvjFlMdFfQwV5hbM81WDp1DjTXDuJUcRA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-06T09:03:29Z"
  mac: ENC[AES256_GCM,data:X21AT/hnJ/v7G+fqVXqkEibe1GCIC+eNtN0AI+h3H+9yagGRr8GfnBoE/pXVBrB3eR9B4luRCDTyDVL+BqUwQNzLRejbvf2Ekx+sQvT9zFQBLIzb0ixdZP5H9P6c8XynR1wvmxBDXABbOp8JghKw1dlhayyUyyYyHKFwXwgptRM=,iv:dYQFj1n7Gxiy4IadT57wwvz9TXXVOcneDNT0mTvWn2s=,tag:D8RnLQIRjEmaLUOte+5rOA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.9.4
