gallery-dl-config: ENC[AES256_GCM,data:Vh6/d0IVriMEYnBdoOrNi50fPL+JsUSl4lB4HePi9HHe4rpeLOM3Cz/ROE3tw8/nOR5ORN53ZaLI7+Af+APsNgYGqo3f8+/6SG4k2L6ALfH2,iv:BwtOBIhImHEofDFbsJSVsMersCuDG+Y6CYILcULlVhU=,tag:yi7PonijQZFJNSPmvs0xaw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age10fy49p7faufe5533rxgshwjn9kr3aqcxjyqk6ty26j99w50dkswsvn2maq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpMTljdmpkQTV3ZnJWWlN0
        WnFtMmtHdXRweFZuWGFGdUtaSlduRitOM3hVCmg5aktPenphTEFyMGJYamQ5dEEv
        eVJtcEE2TDQwcnF5ZzVVVFdtdHlxWGsKLS0tIGJsQ3RZL0tGQ1orcmJQenhlbWxZ
        cU1NN1ZFNGRmb0tFVThDZ05XSDhmTVEKy6AthwyXPDu286ZXZVsBO3e4wMx9DjKG
        7toyzhd922IhSUg4L8yvrcutg7pDS3cwKRusfVHmjuPsRTzPqNg4JA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1lx7mrr66ewummv3mqp4wesq57w0rld8hsujcqcrnnedgjpy7fv2qlkrqk2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWV3BDbU1qUDRWR09XNnpR
        WWFEUmlXakxCZzk1UndtakJRRExDMHFYZ3c0CmdZbzI4U0dtais2YWxaOFJmNzl6
        SVQwYUZxSldXaldEc0NPc0g0K202NUEKLS0tIG1ncnFKdC9Ndi9pbHV6OHhRd2hR
        Rmg4bHN6Unl0b1VkOXhlRmlQbk1pZG8K1f9vp994dELuEknEyBoXESNPzPrzeRcW
        4iQVFrfFVH5Hb86UNQlnURATZHwZlSE7NgBy1dVU4Z3DT8bcg8KpfA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1e7mhx6p2wmnl72c3k3nxajaxurmh63vn27l2kcrxt8xape6mq4dqrpvjnq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRV0k2MnpHUytKUk9pRjFk
        Z2VEWCswV1JGU3BHMUVuNWRLQU1zbDVIYkFJCi9BNTZJYmlKWkwza1BMUVhxZEFv
        Y1ZJY29xN0QxaXNNdkdyWkFlTGNmd0kKLS0tIEZWdkltaVVNd1dIOVBRMFFCZTBx
        YkVLY2VFM2N2L3hNOVJGSHJnd1pGQlUKkkIfaOmd2lD3aKxGaRR258aXMoDfAEKr
        YrNag2GAOwVDuV/dyD/se2TaN8w80c19DZa8e/yiE6R3m86p5qsuQQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-06T09:03:29Z"
  mac: ENC[AES256_GCM,data:X21AT/hnJ/v7G+fqVXqkEibe1GCIC+eNtN0AI+h3H+9yagGRr8GfnBoE/pXVBrB3eR9B4luRCDTyDVL+BqUwQNzLRejbvf2Ekx+sQvT9zFQBLIzb0ixdZP5H9P6c8XynR1wvmxBDXABbOp8JghKw1dlhayyUyyYyHKFwXwgptRM=,iv:dYQFj1n7Gxiy4IadT57wwvz9TXXVOcneDNT0mTvWn2s=,tag:D8RnLQIRjEmaLUOte+5rOA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.4
