gallery-dl-config: ENC[AES256_GCM,data:fof+k7UG/nDAEAa51F1XQx777uIo4ZsVW1lzxWpXHn5fixvdBtis1geVGSfCDoHhZDDo3DmBUdwujhy5bizak2U2iTiJp2gEbLAvSWKs3cnzLkWAelHHsvFrVNFU0s1aZwH86fg3El+Lebj6IoTo1NxFNBcUHYf3EkYK+7I6nGAEdx456sdodoTzyJ9A3M3O02d5DVT8V7GwGWZUTBUWzC/zcl2Q1yGe2chOrlWqTWK2gw6DdYXcbRldKzLuj46YECl6CmAwna+dcHNynoBcoEbAx/HsXVAqizdfER7wa4wsZ49ht9pq056gSzrrrdO9SPNEuFEQ3YkZfOszwqtS4xQfgm3XPjvIAU7hFYhPLvRHoHbGLACO9w==,iv:1nKM1KN36Hk27J6AzLOELodHT/sbkraKnZDCBagHDxo=,tag:k+ELy5kPDMaAG8VHnmuwVg==,type:str]
sops:
  age:
    - recipient: age1amgta8nhsxfm3wu9xa4yhwppway52ap7rj0yjhcrjp9sz6e0gcdqpl6xp3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUE93NytzcDZMVGJBM25N
        VlBQTG9tL0kxRkhPY2F2VXpuK2VWQzFEQjFZCk1PdTBkc0VQb3FMZDRKYklMVjJi
        UStlL0U4YXYxaW5vbzdTU2wrUXN0YzgKLS0tIFI4SVp3cG0zVlBzenROZUs0RE8r
        RklubWVGNU9XZGdId2dtYy84TGh2aVEKaovryxQYG61PwqS/OVOqcvqLrm2mmgIF
        BZkCMnHGjDnDVNPf6fyc4cA0KuSFf1wPqHdBWStkVeTdnE0kx64Llg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1e7mhx6p2wmnl72c3k3nxajaxurmh63vn27l2kcrxt8xape6mq4dqrpvjnq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwVHZuT0ErZVlyWU5vVlVJ
        QjVQdURGY2I0cFUzcnlFY0FheU9tL3FPbTJRCjRmSjhpeGlOZ3JIazZKd0xJWStJ
        bnN3Mk1NazkxcFFmNlhLWXU0TnhiN1EKLS0tIEM1YUZhR0t6Tlh6ekE5azBxUkdM
        Q25POGFHYkYwelRvZGliRUFiMFNsblEKvndjbGZaHiuLpsrZ1omJz/w4oAw8idrF
        dc3Y/EFlEDinorWstdLcXfVqr8KBFAUpD/Yc/W3lcdw3CCVU34UsmQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1v6ak02xxkkmlh42c7vul75twymkq427kyv5pa99ws44frwxn752sure46u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZldGNVpsNFhjYWZHbWZp
        NWkxeExzZlBtRU1YU0FBOGVoc2V2QkJuaG5ZCm94MmVaanRkRTRxVElDQXN5SHV1
        R0FLWkFKWW8yTWlwbmIwUVdKZmpGWDAKLS0tICtsd3NWb2U2a2tzSXJlMEEzN05J
        Q3pydnRmZUJxc204eDZYVXZJdm1TT2MKGMQAPL8QtTbmDp6jI++MJ1qw4v69WPHU
        m2YEwzV86nv1EZ+5I0fmeWV4/iMVAbg2HH0xg+vJKLCqsKHMoIt6tA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age10fy49p7faufe5533rxgshwjn9kr3aqcxjyqk6ty26j99w50dkswsvn2maq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzanZWL0NvdmN4Zm4zNnJx
        Z3ByUzM5bDJEeUE5eURCQk5WYUs2QldrRzJRClFiMk81YmVvK3pueFJWOUJTL3Bp
        eDFRd1I1K3l5WnphcFZRcmRxcS9LejgKLS0tIDFRSzljSzgxOEhxb3FkenIxTnkr
        dSsxZHhlRVoyY002bWdXbkg4KzFyOTgK8VqIx1gH9DH29+C60ySA7BuhN9bDqnph
        wmlfOYyVz1spz4ngQueR28J1gQWkI5Mp08Vx4yIisS+r/M7aoy4OOw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-25T17:18:15Z"
  mac: ENC[AES256_GCM,data:3MEyGwTu4d0D51CzhjUq1AzCqGT1vQ3in9YlAgXeH/BTBiiSxVG8Ye6Vdo0ZjDj8ggRBymADmZcjRAvnUygzqgIGL2/FWxJJa59gx0X010WzrC177gKichTMujbBza/KZIvAZDu7OTnxO938wop9i4fvcepq0zE3QvX2hD61kiQ=,iv:8fYAxbOFNh9mJsgIA8fBAAGnWP1CY7DZUHw8CJSAkn0=,tag:Oe+MGIKTrdOX4XHM2/tQjA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
