gallery-dl-config: ENC[AES256_GCM,data:Vh6/d0IVriMEYnBdoOrNi50fPL+JsUSl4lB4HePi9HHe4rpeLOM3Cz/ROE3tw8/nOR5ORN53ZaLI7+Af+APsNgYGqo3f8+/6SG4k2L6ALfH2,iv:BwtOBIhImHEofDFbsJSVsMersCuDG+Y6CYILcULlVhU=,tag:yi7PonijQZFJNSPmvs0xaw==,type:str]
sops:
  age:
    - recipient: age10fy49p7faufe5533rxgshwjn9kr3aqcxjyqk6ty26j99w50dkswsvn2maq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1WVVLS3pka1ZRcnM2UzEz
        V1hKWHVaUnlvTVV2RnZTRVo0aWx2TlN3TFNJCmRGTFVxSE1oWDVrUEl3Rkx4NXJy
        V01udnU4NTU4NFZMWnRuSnQ3WWtPTE0KLS0tICtoZ0F2VEFycEU2RmN4bmtOT25p
        MmJPZjlKU2JBVGlLRzZJbWxENW1FWFUKELzJlgZjJKdkNh8RkO/eyhYc/gibUh6V
        ir+UOp3Bs6K5+ZgcIkx+t0tjCwvDHJ/foL4X0CCQWBLbyd3P9RFF+A==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1lx7mrr66ewummv3mqp4wesq57w0rld8hsujcqcrnnedgjpy7fv2qlkrqk2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHN3VscjkyWWZxTG9HbG9a
        STJHTWFiOXd3QTZzbDd3cW9DbjlPWkZGVGlBCkRiWHBDcDl5TndGUkZxVFpsZlpZ
        dEJjRWFYYTJNaDBRVHpCZCtBV3VybVkKLS0tIGlnWHRCRDJWaWVBTnp5ZFFza29z
        RHBFYlBPeE81ejZ2U0JqTW5kckdyWmsKoIyALc0WtW0X+3FrtPx7jdvps56/sHzq
        imNwoJsuw6B/TZF/x/S41MfjMEjvW0hcJDuTSIUsQgb8WFz2h8Ea7g==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1e7mhx6p2wmnl72c3k3nxajaxurmh63vn27l2kcrxt8xape6mq4dqrpvjnq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsMkxpakdFZEdXQmt3bjZm
        L1VSRVJsOUtSNTVBYng3YVNEOE01ZldiQlN3CmVnSnFVY1FBWTlDcllqcnpsdFRY
        VGJqWE14Z0lMemxydEl4VXFDVklzblEKLS0tIHk2dHlyYWtyeUlMcHZ0S09QT2VM
        VmZuQlQ0QlZBSGFHT2c1RkpkeHgyODAKdgW6YoFWVyT88TTgdNxgNV2FlYVwCZSV
        jIYJvTFRDYHHuku5R4zVq78mHDl0B40hJPPD45OxMlUWRYSkr0OImA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age17ud6tcqvsy480s64glfgn594nzar8ca2fl3dwd92l3gwa2sg2qrs8qgdyg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVVN2VFAxaC9objhHRXN2
        QlhXVFlpTG50YU1TMGlzanhDdXdlekRrMGhzCjdlYVNSOVFRTkZGNGNBM3JucFVm
        cGxjbDVRRWhjNWU3S1BJbUhUZy8veHMKLS0tIFMyQ2IwalZRdFUrKzAvaUNIVHVY
        VHUxWlhYZlcxTnJTWUNBR0UrKzFjdTAK+Zl0kFnrql+YuOU5wjUowyDQwExxdT8q
        OSM1ickWfJXnY6twO0xRUuTkLAJnukg4Njkad6cI92nxI9pH1vTqAQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-06T09:03:29Z"
  mac: ENC[AES256_GCM,data:X21AT/hnJ/v7G+fqVXqkEibe1GCIC+eNtN0AI+h3H+9yagGRr8GfnBoE/pXVBrB3eR9B4luRCDTyDVL+BqUwQNzLRejbvf2Ekx+sQvT9zFQBLIzb0ixdZP5H9P6c8XynR1wvmxBDXABbOp8JghKw1dlhayyUyyYyHKFwXwgptRM=,iv:dYQFj1n7Gxiy4IadT57wwvz9TXXVOcneDNT0mTvWn2s=,tag:D8RnLQIRjEmaLUOte+5rOA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.9.4
