gallery-dl-config: ENC[AES256_GCM,data:Vh6/d0IVriMEYnBdoOrNi50fPL+JsUSl4lB4HePi9HHe4rpeLOM3Cz/ROE3tw8/nOR5ORN53ZaLI7+Af+APsNgYGqo3f8+/6SG4k2L6ALfH2,iv:BwtOBIhImHEofDFbsJSVsMersCuDG+Y6CYILcULlVhU=,tag:yi7PonijQZFJNSPmvs0xaw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age10fy49p7faufe5533rxgshwjn9kr3aqcxjyqk6ty26j99w50dkswsvn2maq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqSEx0YjVJeU9EQXFaSlJj
        OUMwT3E4bkZEOGI4bGk5Z01IRDhXTHVwWDJVCi9pSUh6akVYYklMbHpha1lCWE5N
        VnQveUdNczlVcnNDQm8vYytxTFFKS3MKLS0tIGg5OEU5TDVveUtMSUNWSDNHVEF5
        cWU0Wms3MEd6QVRKdHRGV085VlZrUE0Kf/AHqqZrLJwnozptHnqVVkO7u8Bm6NYq
        0zspaSYB3rInWFcYRiGL/ShZaCQoKgC418Iy3IIqAEL5F3HJBFnO7Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1lx7mrr66ewummv3mqp4wesq57w0rld8hsujcqcrnnedgjpy7fv2qlkrqk2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnUzVxWXB3VEtYTmRvZE5Y
        MXBHd2xuOVh0UUh2NDFsOWcrdEVZa0lQc1RRCkNIRGVSRzJ5cUhBL3Y2OW9Rc0JR
        M3hGYWtXWkJLcnBkNHQ4YVVSTXQ3Uk0KLS0tIEMyUytEQkpYb1dEWVU5VXFmaldm
        ZVNkZDdVMGZhNEg4QU1tYnhFUklRakEKJMu99zadEdLk2U923DD5pos+vYy6JsZw
        f9hfhiEhGTRh0ztF1Jw3byHqFixhEkgm20vhwnSRq3TuvJRnviFQSA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-06T09:03:29Z"
  mac: ENC[AES256_GCM,data:X21AT/hnJ/v7G+fqVXqkEibe1GCIC+eNtN0AI+h3H+9yagGRr8GfnBoE/pXVBrB3eR9B4luRCDTyDVL+BqUwQNzLRejbvf2Ekx+sQvT9zFQBLIzb0ixdZP5H9P6c8XynR1wvmxBDXABbOp8JghKw1dlhayyUyyYyHKFwXwgptRM=,iv:dYQFj1n7Gxiy4IadT57wwvz9TXXVOcneDNT0mTvWn2s=,tag:D8RnLQIRjEmaLUOte+5rOA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.4
