gallery-dl-config: ENC[AES256_GCM,data:Vh6/d0IVriMEYnBdoOrNi50fPL+JsUSl4lB4HePi9HHe4rpeLOM3Cz/ROE3tw8/nOR5ORN53ZaLI7+Af+APsNgYGqo3f8+/6SG4k2L6ALfH2,iv:BwtOBIhImHEofDFbsJSVsMersCuDG+Y6CYILcULlVhU=,tag:yi7PonijQZFJNSPmvs0xaw==,type:str]
sops:
  age:
    - recipient: age1amgta8nhsxfm3wu9xa4yhwppway52ap7rj0yjhcrjp9sz6e0gcdqpl6xp3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUE93NytzcDZMVGJBM25N
        VlBQTG9tL0kxRkhPY2F2VXpuK2VWQzFEQjFZCk1PdTBkc0VQb3FMZDRKYklMVjJi
        UStlL0U4YXYxaW5vbzdTU2wrUXN0YzgKLS0tIFI4SVp3cG0zVlBzenROZUs0RE8r
        RklubWVGNU9XZGdId2dtYy84TGh2aVEKaovryxQYG61PwqS/OVOqcvqLrm2mmgIF
        BZkCMnHGjDnDVNPf6fyc4cA0KuSFf1wPqHdBWStkVeTdnE0kx64Llg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1e7mhx6p2wmnl72c3k3nxajaxurmh63vn27l2kcrxt8xape6mq4dqrpvjnq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwVHZuT0ErZVlyWU5vVlVJ
        QjVQdURGY2I0cFUzcnlFY0FheU9tL3FPbTJRCjRmSjhpeGlOZ3JIazZKd0xJWStJ
        bnN3Mk1NazkxcFFmNlhLWXU0TnhiN1EKLS0tIEM1YUZhR0t6Tlh6ekE5azBxUkdM
        Q25POGFHYkYwelRvZGliRUFiMFNsblEKvndjbGZaHiuLpsrZ1omJz/w4oAw8idrF
        dc3Y/EFlEDinorWstdLcXfVqr8KBFAUpD/Yc/W3lcdw3CCVU34UsmQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1v6ak02xxkkmlh42c7vul75twymkq427kyv5pa99ws44frwxn752sure46u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZldGNVpsNFhjYWZHbWZp
        NWkxeExzZlBtRU1YU0FBOGVoc2V2QkJuaG5ZCm94MmVaanRkRTRxVElDQXN5SHV1
        R0FLWkFKWW8yTWlwbmIwUVdKZmpGWDAKLS0tICtsd3NWb2U2a2tzSXJlMEEzN05J
        Q3pydnRmZUJxc204eDZYVXZJdm1TT2MKGMQAPL8QtTbmDp6jI++MJ1qw4v69WPHU
        m2YEwzV86nv1EZ+5I0fmeWV4/iMVAbg2HH0xg+vJKLCqsKHMoIt6tA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age10fy49p7faufe5533rxgshwjn9kr3aqcxjyqk6ty26j99w50dkswsvn2maq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzanZWL0NvdmN4Zm4zNnJx
        Z3ByUzM5bDJEeUE5eURCQk5WYUs2QldrRzJRClFiMk81YmVvK3pueFJWOUJTL3Bp
        eDFRd1I1K3l5WnphcFZRcmRxcS9LejgKLS0tIDFRSzljSzgxOEhxb3FkenIxTnkr
        dSsxZHhlRVoyY002bWdXbkg4KzFyOTgK8VqIx1gH9DH29+C60ySA7BuhN9bDqnph
        wmlfOYyVz1spz4ngQueR28J1gQWkI5Mp08Vx4yIisS+r/M7aoy4OOw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-06T09:03:29Z"
  mac: ENC[AES256_GCM,data:X21AT/hnJ/v7G+fqVXqkEibe1GCIC+eNtN0AI+h3H+9yagGRr8GfnBoE/pXVBrB3eR9B4luRCDTyDVL+BqUwQNzLRejbvf2Ekx+sQvT9zFQBLIzb0ixdZP5H9P6c8XynR1wvmxBDXABbOp8JghKw1dlhayyUyyYyHKFwXwgptRM=,iv:dYQFj1n7Gxiy4IadT57wwvz9TXXVOcneDNT0mTvWn2s=,tag:D8RnLQIRjEmaLUOte+5rOA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.9.4
