gallery-dl-config: ENC[AES256_GCM,data:FyLqZqurPphg/7l8RAxvJN230INnIIXZaSJTTjEooY8qykv8hXT/3oi6OHxX13kRVIlblKDZnEoR03PEVqBOV0l73vyOxSB2bha7+bmf0G6brxa9s7X6Rsc0FmqdLWuuaHnSfS2zpGe/AC+NMqHn9sXRe+9NpaQFfrTkvZ/T5v4jBWc0ERuGy72wTNOAu2AfcYsxzJBj4q24RMgbjcSssVJuEIt7ExMxGhYOWM1hBqNFZxLXynHmYXcA/wHZxa6ZFJ2QZXj9cSWuN2Y3VHjv7TxfjnAlQNJoJ6lj5TaFRfR6Sq+KNtRQ6Mz2j9hF8pDYOniFpSVnKtmvXtU8oyQ5tGPEIYX5FqhrYuAtdee3wqPlUSf6+x/dNy0WtDdeF1ROnHmsXH37f0oAdTDAnQPlmeZS0w4qN/0=,iv:RDNyA//Ph/deWkipSxH+mehEnG2RHmge7cFSyZFbAW4=,tag:7/hyKdKcTHErvtWowL2YEQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age10fy49p7faufe5533rxgshwjn9kr3aqcxjyqk6ty26j99w50dkswsvn2maq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqSEx0YjVJeU9EQXFaSlJj
        OUMwT3E4bkZEOGI4bGk5Z01IRDhXTHVwWDJVCi9pSUh6akVYYklMbHpha1lCWE5N
        VnQveUdNczlVcnNDQm8vYytxTFFKS3MKLS0tIGg5OEU5TDVveUtMSUNWSDNHVEF5
        cWU0Wms3MEd6QVRKdHRGV085VlZrUE0Kf/AHqqZrLJwnozptHnqVVkO7u8Bm6NYq
        0zspaSYB3rInWFcYRiGL/ShZaCQoKgC418Iy3IIqAEL5F3HJBFnO7Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1lx7mrr66ewummv3mqp4wesq57w0rld8hsujcqcrnnedgjpy7fv2qlkrqk2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnUzVxWXB3VEtYTmRvZE5Y
        MXBHd2xuOVh0UUh2NDFsOWcrdEVZa0lQc1RRCkNIRGVSRzJ5cUhBL3Y2OW9Rc0JR
        M3hGYWtXWkJLcnBkNHQ4YVVSTXQ3Uk0KLS0tIEMyUytEQkpYb1dEWVU5VXFmaldm
        ZVNkZDdVMGZhNEg4QU1tYnhFUklRakEKJMu99zadEdLk2U923DD5pos+vYy6JsZw
        f9hfhiEhGTRh0ztF1Jw3byHqFixhEkgm20vhwnSRq3TuvJRnviFQSA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-09-01T07:42:53Z"
  mac: ENC[AES256_GCM,data:zgSEwn0JGFigNVC63cVMpj/fheL4kbiJkXAUjJMUMO0DOc+1nhDSXdLezysiHrO5czwTmUItMLDnl3rskxoFDm0LjofW2OXIypBOWzkaWIwquN8huqm9VWY3/G33XxDMVtaSuFWl3J+MKa0r4ZLE1tctwr/oCN4hO9PtXeJp7mA=,iv:BgJ+HPvX5duS0D/cd5ufLRVivXearvYCqDPD6Y2Qggw=,tag:4XPK0/G/adJuu2hnORE6iQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.0
