{
	"data": "ENC[AES256_GCM,data:jSpR7kLn+0BOeK6y8lUOqsXIn6bfQmnTQCMbP9yDLMsJaATbeM+++axK8abl6k0Ib+BMrFfZG7I/XOvnUwmHbBnu+wjnqyLy6+dxVqR81wQbl0+0UTxE+q/nYFEgClCXeYq6H2bvz1cnFt2Vm3CqmBjxTeFG5yNskwSfZShkK7ASU5tqX5Fy+K5cROVHR5mq9VKA1BFoWPoU9/cFuhg6g4xIJgE75hHcuLt7XXACPsipvf8cXvDk1un9tvC1bhHkJZyIdo8gEFSvGuxH9HaTEBYJ68CS2X3S/IRvd8/pThC0jW7s4hvJIX2r2S93dcKQuQZenlvOveXwfdSg0Dhnjfu5AcB72tMaZuzrFXbsECd51WckKFMi5K3E7iKosmyLUQKG5Q26ASYIe3KzqA85XpZdeSTfa5tLZhC1xG7KoIztoz/CEUcd7N2xnPMI3P/4Zxxg1A5YSAaqPo8X3H+2WHO/fcsSpCFBvn2Jx3rC6QwbtV1kx2sWN4KNABCkJrbBC4DMXxXLZwcczdZyelGyCtcBtQzcYR21iu9GUZncwtOBbPB2tA+Jz6V21SglnaQzN8Aygclh3BAEvI6EgTCFn1BzRlP+uKq5K34otwNBeVAnKXqISTgWH8ZwsLAKPPdwhFfob7Xa22M+XdTTNwqIWvlDFiShFJvIjoftFF38Tz+5bkiTb3vGFIP+wdbXXjlLBeojlsNzi/LxJcRX,iv:ADTWVD9LFagbmKL7Bcgm/bIr2f/Wlk+KfEX2S0D8Lro=,tag:of6ZxdEvtSiPXsNa54cm4Q==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age1y7arunqzyjjdyspx46z20x6qadxpxfu5z59qe74tn4re375ctg7qtj48p3",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBML2I3SVN0SytVM2RJSDdL\nRlI5RTdXN0xOejRscHRocUJadDNHbGl3SWdJCnVkMkFDSkY3NHVkeWVBM2FaMlVG\neGtHQ2VsTURWTmlkd1RWL29YSzBpYk0KLS0tIGJGdy96OERvN0FieW94MEFkWC9y\neWkwV0JDYk90b05OdW82QmxCM05odXMK3x6rxOVEwBY+gXtpUNgmtdZqhOhBkim8\n7giJnnuyr8quLl/jieOPmWJSauOpoEtV2HTMYa09TD0/jw/sya1oyg==\n-----END AGE ENCRYPTED FILE-----\n"
			},
			{
				"recipient": "age1dvrymsl5xk26pkznk5kljqssnkvae2ftsawx96n4r43p3cfzyv4qtr67qj",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYdjYzdmNKb2NGYU1ZaFpD\nck5FUmlJOVBuc3pKcVpCd1laOW1CeFJnVGhjCmJ5MmI1V0Y1dzljUWtMMC9ybzhV\nMElBMUt3ZzcxTmQ2WmxUZ0VMWHd6QjAKLS0tIG5kSjA4RkhrTmNXdXRtb2xNQ21C\nRWwxby9yenVHU3pWMUNNWG5QdE1wbzAKIs5YRaUVHdk9iJflU8VrbUD0H0NRQMxA\nntY137s17GIY4pdoTFrEmmTdIjZXgmvMWLUVynTeog2KjcoF45JrtA==\n-----END AGE ENCRYPTED FILE-----\n"
			},
			{
				"recipient": "age10fy49p7faufe5533rxgshwjn9kr3aqcxjyqk6ty26j99w50dkswsvn2maq",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXS1NGbTlMMDdZTnNlS000\neVZob3dTUzBibEhHOE1uWUt2U0hQVjlHb2tVCmFuV0trVDF1OXN4WEpNRW5DWit0\nSllpQVYyZll2c1RMN3pNMHo3Q1o5eTAKLS0tIEpoazBGZWVjdUFYL2tBVUxvaDNN\nZU9wUmFVZFg1TDZDZkRQSitVa3dpakEKhA+X2IpJ0xn60M3pzF6kmrJP75P4763e\nTJE4fnWmibjYOnixtKysGgW2FuVJM1oGlTHVten8pyFRV09x4MvWZw==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2024-03-13T07:38:06Z",
		"mac": "ENC[AES256_GCM,data:vSWy11Z825sYqbmchPWzrZcSWzgoyO30xVGgXmmJiWnSj8D3EkD0PILW3DCtp9PWag1hhYbEwXPSR+If+ddsrFINq6Y0U4xKvbL7TmKTQHZ4TJk3zVNIi84QpvwuHP9awR0P6nZVK4WKj9KAhMJ9xCRZWJMhYeeOX/FOmXr8Ay4=,iv:3aswGEZk5ckuJPP54CXgw/uDa8UWIeBi6d3m36lTE4I=,tag:OucC8zLHPtiFSINk2WiVyw==,type:str]",
		"pgp": null,
		"unencrypted_suffix": "_unencrypted",
		"version": "3.8.1"
	}
}